version: 2.1
jobs:
  build:
    environment:
      CI: True
    docker:
    - image: cimg/node:12.16
    steps:
    - checkout
    - run:
        name: npm install, build, and test
        command: |
          npm ci
          npm run build --if-present
          npm test
workflows:
  Node_CI:
    jobs:
    - build